server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schoolsys?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: deng123
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 300
      initial-size: 20
#  redis:
#    database: 5
#    host: 47.106.111.54
#    password:
#    port: 6379
#    timeout: 3000
#    pool:
#      max-idle: 500
#      min-idle: 50
#      max-active: 2000
#      max-wait: 1000
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  jackson:
    serialization:
      indent_output: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#  security:
#    filter:
#      order: 5
logging:
  config: classpath:log4j2.xml

database:
  pagefix: offset
